### ISSUE TITLE
Error when running locally

### ISSUE THREAD

**Issue by akieling** [Apicurio/apicurio-registry-operator#26]
I followed the installation steps described in the README.md file:

- Create service account, roles, and role bindings
- Create ApicurioRegistry CRD
- Run operator: `operator-sdk run --local`
- Create ApicurioRegistry CR: `oc create -f deploy/crds/apicur_v1alpha1_apicurioregistry_cr.yaml`

Log:
```
E0603 15:56:57.751926   67102 runtime.go:78] Observed a panic: &net.DNSError{Err:"no such host", Name:"kubernetes.default.svc", Server:"127.0.0.1:53", IsTimeout:false, IsTemporary:false, IsNotFound:true} (lookup kubernetes.default.svc on 127.0.0.1:53: no such host)
goroutine 271 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1494580, 0xc00031c1c0)
	/home/akieling/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/akieling/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1494580, 0xc00031c1c0)
	/usr/lib/golang/src/runtime/panic.go:969 +0x166
github.com/Apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry.inClusterConfig(0x1516820, 0xc0003b8660, 0xc000671560)
	/home/akieling/dev/projects/apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry/clients.go:40 +0x16a
github.com/Apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry.NewClients(0xc000398a80, 0xc00031aa80)
	/home/akieling/dev/projects/apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry/clients.go:26 +0x55
github.com/Apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry.NewContext(0x1841f20, 0xc00024e9c0, 0xc00025aa80, 0x184d840, 0xc0003b85e0, 0x1854e60, 0xc0004641b0, 0x1)
	/home/akieling/dev/projects/apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry/context.go:39 +0x176
github.com/Apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry.(*ApicurioRegistryReconciler).Reconcile(0xc0004f3d10, 0xc0003e9ba0, 0x11, 0xc0003e9b80, 0x18, 0x0, 0xbfae1a7e69721039, 0xc0005ae240, 0xc0005ae128)
	/home/akieling/dev/projects/apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry/control_loop.go:59 +0xf01
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00024e9c0, 0x14bb400, 0xc0003b84a0, 0xc000587e00)
	/home/akieling/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00024e9c0, 0xc000587f00)
	/home/akieling/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00024e9c0)
	/home/akieling/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005bc0e0)
	/home/akieling/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005bc0e0, 0x3b9aca00, 0x0, 0x1, 0xc00058e1e0)
	/home/akieling/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0005bc0e0, 0x3b9aca00, 0xc00058e1e0)
	/home/akieling/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/akieling/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:193 +0x305
panic: lookup kubernetes.default.svc on 127.0.0.1:53: no such host [recovered]
	panic: lookup kubernetes.default.svc on 127.0.0.1:53: no such host
```

**Comment by akieling** [comment]
Any update on this issue?
